### ISSUE TITLE
[IDEA] Publish for Single File Html

### ISSUE THREAD

**Issue by kookma** [ahanniga/tiddly-dark#1]
Hi Aidan,
 This is very nice theme and I highly recommend to publish a version for single file (emty.html)
 I realized that I need to import two tiddlers

 - Theme Tweak
 - GitHub Dark Palette

It needs a font file, which I think one can embed it! (see here: http://kookma.webfonts.tiddlyspot.com/)

I was able to download and run the Node.JS version and I will put a note in community forum!

**Comment by ahanniga** [comment]
Hi Mohammad,

You should be able to get the same theme on a plain-vanilla Tiddlywiki by:

- Dragging the "Github Dark" palette (Control Panel -> Appearance -> Palette) and activating it.
- Import the "Theme Tweaks" tiddler
- In Control Panel -> Appearance -> Theme Tweaks, set Fluid Story / Fixed Sidebar. And set the Sidebar width to 30%

For editor font I do include hack-regular.woff/woff2 in the files/ directory, but perhaps in single-html it does not work as expected. Thanks for the link, will read through it.

**Comment by kookma** [comment]
I announced this lovely theme on you behalf on the forum

https://talk.tiddlywiki.org/t/github-dark-theme/1826

Thank you for publishing this nice theme!
