### ISSUE TITLE
[ISSUE] Low Contrast in 

### ISSUE THREAD

**Issue by kookma** [ahanniga/tiddly-dark#3]
1. Create a new Tiddler 
2. Keep it open in edit mode
3. From Sidebar > Tools tap > Close all
4. See the below image

![image](https://user-images.githubusercontent.com/830394/146058413-f88b1fe6-c7c2-4aea-9c6e-8b232cfb75b9.png)

**Expected Behavior**
The contrast shall be enough to be able to read the text!

**Comment by ahanniga** [comment]
Good spot, will fix
